import OpenAI from "openai";
import type { ContentGenerationRequest, ContentGenerationResponse } from "./types/editor";

// Initialize OpenAI client lazily to avoid build-time errors
let openai: OpenAI | null = null;

function getOpenAIClient(): OpenAI {
  if (!openai) {
    if (!process.env.OPENAI_API_KEY) {
      throw new Error("OPENAI_API_KEY is not set in environment variables");
    }
    openai = new OpenAI({
      apiKey: process.env.OPENAI_API_KEY,
    });
  }
  return openai;
}

// System prompts for different node types
const SYSTEM_PROMPTS = {
  scene: `You are a creative writing assistant helping authors write story scenes. 
Generate vivid, engaging scene descriptions that show rather than tell. 
Include sensory details and character actions. Keep the tone consistent with the story context.`,
  
  choice: `You are a creative writing assistant helping authors write story choices. 
Generate clear, compelling choice options that give players meaningful decisions. 
Each choice should hint at consequences while being concise.`,
  
  ending: `You are a creative writing assistant helping authors write story endings. 
Generate satisfying conclusions that resolve the narrative threads. 
Provide emotional closure while reflecting the player's journey.`,
  
  note: `You are a creative writing assistant helping authors organize their story notes. 
Generate clear, organized content for story planning and documentation. 
Be concise and structured.`,
};

/**
 * Build context prompt from surrounding nodes and user preferences
 */
function buildContextPrompt(request: ContentGenerationRequest): string {
  let contextPrompt = "";

  if (request.nodeType) {
    contextPrompt += `You are writing a ${request.nodeType} node for an interactive story.\n\n`;
  }

  if (request.contextNodes && request.contextNodes.length > 0) {
    contextPrompt += "Context from connected story nodes:\n";
    request.contextNodes.forEach((node, idx) => {
      contextPrompt += `${idx + 1}. ${node.type}: ${node.title}\n`;
      if (node.content) {
        contextPrompt += `   ${node.content.substring(0, 200)}${node.content.length > 200 ? "..." : ""}\n`;
      }
    });
    contextPrompt += "\n";
  }

  if (request.currentContent) {
    contextPrompt += `Current content to expand or refine:\n${request.currentContent}\n\n`;
  }

  if (request.options?.tone) {
    contextPrompt += `Tone: ${request.options.tone}\n\n`;
  }

  return contextPrompt;
}

/**
 * Generate story content using OpenAI
 */
export async function generateContent(
  request: ContentGenerationRequest
): Promise<ContentGenerationResponse> {
  try {
    const systemPrompt = request.nodeType 
      ? SYSTEM_PROMPTS[request.nodeType] 
      : SYSTEM_PROMPTS.scene;

    const contextPrompt = buildContextPrompt(request);
    const userPrompt = `${contextPrompt}User request: ${request.prompt}`;

    const completion = await getOpenAIClient().chat.completions.create({
      model: "gpt-4o-mini", // Cost-effective option, use gpt-4o for higher quality
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
      temperature: request.options?.temperature ?? 0.7,
      max_tokens: request.options?.maxTokens ?? 1000,
      top_p: 0.9,
      frequency_penalty: 0.3, // Reduce repetition
      presence_penalty: 0.3,  // Encourage topic diversity
    });

    const generatedContent = completion.choices[0]?.message?.content;

    if (!generatedContent) {
      return {
        success: false,
        error: "No content generated by AI",
        generatedAt: new Date(),
      };
    }

    return {
      success: true,
      content: generatedContent.trim(),
      usage: {
        promptTokens: completion.usage?.prompt_tokens ?? 0,
        completionTokens: completion.usage?.completion_tokens ?? 0,
        totalTokens: completion.usage?.total_tokens ?? 0,
      },
      generatedAt: new Date(),
    };
  } catch (error) {
    console.error("OpenAI content generation error:", error);
    
    if (error instanceof OpenAI.APIError) {
      return {
        success: false,
        error: `OpenAI API error: ${error.message}`,
        generatedAt: new Date(),
      };
    }

    return {
      success: false,
      error: "Failed to generate content. Please try again.",
      generatedAt: new Date(),
    };
  }
}

// ------------------------------------------------------------
// Rate Limiting
// ------------------------------------------------------------

interface RateLimitEntry {
  count: number;
  resetAt: Date;
}

const rateLimitMap = new Map<string, RateLimitEntry>();

// Clean up old entries every 5 minutes
setInterval(() => {
  const now = new Date();
  for (const [key, entry] of rateLimitMap.entries()) {
    if (entry.resetAt < now) {
      rateLimitMap.delete(key);
    }
  }
}, 5 * 60 * 1000);

/**
 * Check if a user has exceeded the rate limit
 * @param userId - User identifier
 * @param limit - Maximum requests per window (default: 20)
 * @param windowMs - Time window in milliseconds (default: 1 hour)
 * @returns true if rate limit exceeded, false otherwise
 */
export function checkRateLimit(
  userId: string,
  limit: number = 20,
  windowMs: number = 60 * 60 * 1000 // 1 hour
): { limited: boolean; remaining: number; resetAt: Date } {
  const now = new Date();
  const entry = rateLimitMap.get(userId);

  if (!entry || entry.resetAt < now) {
    // No entry or expired - create new window
    const resetAt = new Date(now.getTime() + windowMs);
    rateLimitMap.set(userId, { count: 1, resetAt });
    return { limited: false, remaining: limit - 1, resetAt };
  }

  // Increment count
  entry.count++;
  
  if (entry.count > limit) {
    return { limited: true, remaining: 0, resetAt: entry.resetAt };
  }

  return { limited: false, remaining: limit - entry.count, resetAt: entry.resetAt };
}
